spring:
  datasource:
    url: jdbc:mysql://localhost:3306/buildz_test
    driverClassName: com.mysql.jdbc.Driver
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: validate
flyway:
  locations: 'classpath:db.migration'
