spring:
  datasource:
    url: jdbc:mysql://localhost:5306/buildz
    driverClassName: com.mysql.jdbc.Driver
    username: buildz
    password: buildz
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.ddl-auto: validate
flyway:
  enabled: true
